const http = require('http');
const fs = require('fs');
const path = require('path');
const { Jimp } = require('jimp');

const PORT = 3456;
const ASSETS_DIR = path.join(__dirname, '..', 'assets');

// Akıllı köşe taramalı şeffaf PNG yapıcı (Flood Fill Alpha Remover)
async function makeTransparentPNG(filePath) {
  try {
    const img = await Jimp.read(filePath);
    const { width, height } = img.bitmap;

    const bgR = img.bitmap.data[0];
    const bgG = img.bitmap.data[1];
    const bgB = img.bitmap.data[2];
    const tolerance = 24;

    function isBg(r, g, b) {
      return (
        Math.abs(r - bgR) < tolerance &&
        Math.abs(g - bgG) < tolerance &&
        Math.abs(b - bgB) < tolerance
      ) || (r > 248 && g > 248 && b > 248);
    }

    const visited = new Uint8Array(width * height);
    const queue = [];

    for (let x = 0; x < width; x++) {
      queue.push(x, 0);
      queue.push(x, height - 1);
    }
    for (let y = 0; y < height; y++) {
      queue.push(0, y);
      queue.push(width - 1, y);
    }

    let head = 0;
    while (head < queue.length) {
      const x = queue[head++];
      const y = queue[head++];
      const idx1D = y * width + x;

      if (visited[idx1D]) continue;
      visited[idx1D] = 1;

      const pIdx = (y * width + x) * 4;
      const r = img.bitmap.data[pIdx + 0];
      const g = img.bitmap.data[pIdx + 1];
      const b = img.bitmap.data[pIdx + 2];

      if (isBg(r, g, b)) {
        img.bitmap.data[pIdx + 3] = 0;

        if (x > 0 && !visited[y * width + (x - 1)]) queue.push(x - 1, y);
        if (x < width - 1 && !visited[y * width + (x + 1)]) queue.push(x + 1, y);
        if (y > 0 && !visited[(y - 1) * width + x]) queue.push(x, y - 1);
        if (y < height - 1 && !visited[(y + 1) * width + x]) queue.push(x, y + 1);
      }
    }

    await img.write(filePath);
    console.log(`[MOMORA] ✨ Arka plan başarıyla şeffaf yapıldı: ${path.basename(filePath)}`);
  } catch (err) {
    console.warn(`[MOMORA] Şeffaflaştırma hatası:`, err.message);
  }
}

const GENERATED_ASSETS_FILE = path.join(__dirname, '..', 'src', 'generatedAssets.js');

let lastGeneratedContent = '';

function updateGeneratedAssetsFile() {
  try {
    if (!fs.existsSync(ASSETS_DIR)) return;
    const allEntries = fs.readdirSync(ASSETS_DIR);
    const pngFiles = allEntries.filter(f => {
      try {
        if (fs.statSync(path.join(ASSETS_DIR, f)).isDirectory()) return false;
        if (!f.endsWith('.png')) return false;
        if (f.startsWith('android-') || f.startsWith('favicon') || f.startsWith('icon') || f.startsWith('splash')) return false;
        return true;
      } catch (e) {
        return false;
      }
    }).sort();

    const lines = [
      '// AUTO-GENERATED BY MOMORA ASSET PIPELINE',
      '// Bu dosya yeni görseller indirildikçe otomatik olarak güncellenir.',
      '',
      'export const generatedAssets = {'
    ];

    pngFiles.forEach(f => {
      const key = path.basename(f, '.png');
      lines.push(`  '${key}': require('../assets/${f}'),`);
    });

    lines.push('};');
    lines.push('');
    lines.push('export function getAsset(name) {');
    lines.push('  if (generatedAssets[name]) return generatedAssets[name];');
    lines.push('  if (name && name.startsWith("blog_")) {');
    lines.push('    if (name.includes("seafood") || name.includes("coffee")) return generatedAssets["blog_healthy_breakfast"];');
    lines.push('    if (name.includes("morning")) return generatedAssets["blog_pregnant_morning"];');
    lines.push('    if (name.includes("contraction") || name.includes("braxton")) return generatedAssets["blog_couple_bump"];');
    lines.push('    if (name.includes("epidural") || name.includes("hospital")) return generatedAssets["blog_hospital_bag_pack"];');
    lines.push('    if (name.includes("breastmilk")) return generatedAssets["blog_breastfeeding_cozy"];');
    lines.push('    if (name.includes("colic") || name.includes("massage")) return generatedAssets["blog_baby_massage"];');
    lines.push('    if (name.includes("sleep")) return generatedAssets["blog_sleeping_crib"];');
    lines.push('    if (name.includes("blues") || name.includes("depression")) return generatedAssets["blog_postpartum_selfcare"];');
    lines.push('    return generatedAssets["blog_pregnant_morning"] || generatedAssets["blog_newborn_hand"];');
    lines.push('  }');
    lines.push('  return null;');
    lines.push('}');
    lines.push('');

    const newContent = lines.join('\n');
    if (newContent !== lastGeneratedContent) {
      fs.writeFileSync(GENERATED_ASSETS_FILE, newContent, 'utf8');
      lastGeneratedContent = newContent;
      console.log(`[MOMORA-WATCHER] 🔄 Kod tabanı güncellendi! (${pngFiles.length} görsel bağlandı: src/generatedAssets.js)`);
    }
  } catch (err) {
    console.error('[MOMORA-WATCHER] Hata:', err.message);
  }
}

const server = http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS, GET');
  res.setHeader('Access-Control-Allow-Headers', '*');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    return res.end();
  }

  // 1. Mevcut Dosya Listesi Endpointi
  if (req.method === 'GET' && (req.url === '/list' || req.url.startsWith('/list?'))) {
    try {
      const allEntries = fs.readdirSync(ASSETS_DIR);
      const files = allEntries.filter(f => {
        try {
          return !fs.statSync(path.join(ASSETS_DIR, f)).isDirectory() && f.endsWith('.png');
        } catch (e) {
          return false;
        }
      });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ files }));
    } catch (e) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // 1b. 3D Model Listesi Endpointi
  if (req.method === 'GET' && req.url === '/models') {
    try {
      const allEntries = fs.readdirSync(ASSETS_DIR);
      const models = allEntries.filter(f => f.endsWith('.glb') || f.endsWith('.gltf'));
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ models }));
    } catch (e) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // 1c. 3D Fetus Viewer Sayfası
  if (req.method === 'GET' && (req.url === '/3d' || req.url === '/viewer' || req.url === '/3d/')) {
    const viewerPath = path.join(__dirname, 'view_3d_fetus.html');
    if (fs.existsSync(viewerPath)) {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      fs.createReadStream(viewerPath).pipe(res);
      return;
    }
  }

  // 2. Asset Dosyası Sunucu Endpointi (PNG, GLB, vb.)
  if (req.method === 'GET' && req.url.startsWith('/assets/')) {
    const filename = decodeURIComponent(req.url.replace('/assets/', ''));
    const filePath = path.join(ASSETS_DIR, filename);
    if (fs.existsSync(filePath)) {
      const ext = path.extname(filename).toLowerCase();
      let contentType = 'application/octet-stream';
      if (ext === '.png') contentType = 'image/png';
      else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
      else if (ext === '.glb') contentType = 'model/gltf-binary';
      else if (ext === '.gltf') contentType = 'model/gltf+json';

      res.writeHead(200, { 'Content-Type': contentType });
      fs.createReadStream(filePath).pipe(res);
      return;
    } else {
      res.writeHead(404);
      res.end('Not found');
      return;
    }
  }

  // 3. Görsel Yükleme Endpointi
  if (req.method === 'POST' && req.url.startsWith('/upload')) {
    const urlObj = new URL(req.url, `http://localhost:${PORT}`);
    const filename = urlObj.searchParams.get('filename') || `image_${Date.now()}.png`;
    const shouldMakeTransparent = urlObj.searchParams.get('transparent') !== 'false';
    const dest = path.join(ASSETS_DIR, filename);

    const writeStream = fs.createWriteStream(dest);
    req.pipe(writeStream);

    req.on('end', async () => {
      console.log(`[ASSET-RECEIVER] 📥 Alındı: ${filename} (Şeffaflaştırma: ${shouldMakeTransparent ? 'AÇIK' : 'KAPALI'})`);
      if (shouldMakeTransparent && !filename.endsWith('.glb')) {
        await makeTransparentPNG(dest);
      }
      updateGeneratedAssetsFile();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok', filename, transparent: shouldMakeTransparent }));
    });

    req.on('error', (err) => {
      console.error('[ASSET-RECEIVER] Hata:', err);
      res.writeHead(500);
      res.end(JSON.stringify({ error: err.message }));
    });
    return;
  }

  res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end('MOMORA Transparent Asset Receiver calisiyor.');
});

server.listen(PORT, () => {
  console.log(`[MOMORA] 🪄 Otomatik Şeffaf PNG Alıcı Servisi http://localhost:${PORT} üzerinde hazır!`);
  // İlk çalıştırmada mevcut tüm dosyaları tara ve bağla
  updateGeneratedAssetsFile();
  // Her 3 saniyede bir klasörü kontrol eden otomatik timer
  setInterval(updateGeneratedAssetsFile, 3000);
});
