const http = require('http');
const fs = require('fs');
const path = require('path');

let Jimp = null;
try {
  const j = require('jimp');
  Jimp = j.Jimp || j;
} catch (e) {
  console.warn('[MOMORA] Jimp modulu yuklenemedi, seffaf PNG donusumu atlanacak.');
}

const PORT = 3456;
const ASSETS_DIR = path.join(__dirname, '..', 'assets');
const QUEUE_FILE = path.join(__dirname, 'generation_queue.json');
const GENERATED_ASSETS_FILE = path.join(__dirname, '..', 'src', 'generatedAssets.js');

// --- QUEUE MANAGEMENT ---
function loadQueue() {
  try {
    if (fs.existsSync(QUEUE_FILE)) {
      return JSON.parse(fs.readFileSync(QUEUE_FILE, 'utf8'));
    }
  } catch (e) {
    console.error('[QUEUE] Error reading queue file:', e.message);
  }
  return { jobs: [] };
}

function saveQueue(queueData) {
  try {
    fs.writeFileSync(QUEUE_FILE, JSON.stringify(queueData, null, 2), 'utf8');
  } catch (e) {
    console.error('[QUEUE] Error saving queue file:', e.message);
  }
}

function getNextJob() {
  const queueData = loadQueue();
  const now = Date.now();
  queueData.jobs.forEach(j => {
    if (j.status === 'processing' && (now - (j.startedAt || 0) > 240000)) {
      console.log('[QUEUE] Resetting timed out job:', j.filename);
      j.status = 'pending';
    }
  });

  const pendingJob = queueData.jobs.find(j => j.status === 'pending');
  if (pendingJob) {
    pendingJob.status = 'processing';
    pendingJob.startedAt = now;
    pendingJob.attempts = (pendingJob.attempts || 0) + 1;
    saveQueue(queueData);
    return pendingJob;
  }
  return null;
}

function updateJobStatus(idOrFilename, status, extra = {}) {
  const queueData = loadQueue();
  const job = queueData.jobs.find(j => j.id === idOrFilename || j.filename === idOrFilename);
  if (job) {
    job.status = status;
    job.updatedAt = Date.now();
    Object.assign(job, extra);
    saveQueue(queueData);
    console.log('[QUEUE] Job ' + job.filename + ' -> ' + status);
    return true;
  }
  return false;
}

async function makeTransparentPNG(filePath) {
  if (!Jimp) return;
  try {
    const img = await Jimp.read(filePath);
    const { width, height } = img.bitmap;
    const bgR = img.bitmap.data[0];
    const bgG = img.bitmap.data[1];
    const bgB = img.bitmap.data[2];
    const tolerance = 24;
    function isBg(r, g, b) {
      return (
        Math.abs(r - bgR) < tolerance &&
        Math.abs(g - bgG) < tolerance &&
        Math.abs(b - bgB) < tolerance
      ) || (r > 248 && g > 248 && b > 248);
    }
    const visited = new Uint8Array(width * height);
    const queue = [];
    for (let x = 0; x < width; x++) {
      queue.push(x, 0);
      queue.push(x, height - 1);
    }
    for (let y = 0; y < height; y++) {
      queue.push(0, y);
      queue.push(width - 1, y);
    }
    let head = 0;
    while (head < queue.length) {
      const x = queue[head++];
      const y = queue[head++];
      const idx1D = y * width + x;
      if (visited[idx1D]) continue;
      visited[idx1D] = 1;
      const pIdx = (y * width + x) * 4;
      const r = img.bitmap.data[pIdx + 0];
      const g = img.bitmap.data[pIdx + 1];
      const b = img.bitmap.data[pIdx + 2];
      if (isBg(r, g, b)) {
        img.bitmap.data[pIdx + 3] = 0;
        if (x > 0 && !visited[y * width + (x - 1)]) queue.push(x - 1, y);
        if (x < width - 1 && !visited[y * width + (x + 1)]) queue.push(x + 1, y);
        if (y > 0 && !visited[(y - 1) * width + x]) queue.push(x, y - 1);
        if (y < height - 1 && !visited[(y + 1) * width + x]) queue.push(x, y + 1);
      }
    }
    await img.write(filePath);
    console.log('[MOMORA] ✨ Arka plan seffaf yapildi:', path.basename(filePath));
  } catch (err) {
    console.warn('[MOMORA] Seffaflastirma hatasi:', err.message);
  }
}

let lastGeneratedContent = '';
function updateGeneratedAssetsFile() {
  try {
    if (!fs.existsSync(ASSETS_DIR)) return;
    const allEntries = fs.readdirSync(ASSETS_DIR);
    const pngFiles = allEntries.filter(f => {
      try {
        if (fs.statSync(path.join(ASSETS_DIR, f)).isDirectory()) return false;
        if (!f.endsWith('.png')) return false;
        if (f.startsWith('android-') || f.startsWith('favicon') || f.startsWith('icon') || f.startsWith('splash')) return false;
        return true;
      } catch (e) { return false; }
    }).sort();

    const lines = [
      '// AUTO-GENERATED BY MOMORA ASSET PIPELINE',
      '// Bu dosya yeni gorseller indirildikce otomatik olarak guncellenir.',
      '',
      'export const generatedAssets = {'
    ];
    pngFiles.forEach(f => {
      const key = path.basename(f, '.png');
      lines.push("  '" + key + "': require('../assets/" + f + "'),");
    });
    lines.push('};');
    lines.push('');
    lines.push('export function getAsset(name) {');
    lines.push('  if (generatedAssets[name]) return generatedAssets[name];');
    lines.push('  if (name && name.startsWith("blog_")) {');
    lines.push('    if (name.includes("seafood") || name.includes("coffee")) return generatedAssets["blog_healthy_breakfast"];');
    lines.push('    if (name.includes("morning")) return generatedAssets["blog_pregnant_morning"];');
    lines.push('    if (name.includes("contraction") || name.includes("braxton")) return generatedAssets["blog_couple_bump"];');
    lines.push('    if (name.includes("epidural") || name.includes("hospital")) return generatedAssets["blog_hospital_bag_pack"];');
    lines.push('    if (name.includes("breastmilk")) return generatedAssets["blog_breastfeeding_cozy"];');
    lines.push('    if (name.includes("colic") || name.includes("massage")) return generatedAssets["blog_baby_massage"];');
    lines.push('    if (name.includes("sleep")) return generatedAssets["blog_sleeping_crib"];');
    lines.push('    if (name.includes("blues") || name.includes("depression")) return generatedAssets["blog_postpartum_selfcare"];');
    lines.push('    return generatedAssets["blog_pregnant_morning"] || generatedAssets["blog_newborn_hand"];');
    lines.push('  }');
    lines.push('  return null;');
    lines.push('}');
    lines.push('');
    const newContent = lines.join('\n');
    if (newContent !== lastGeneratedContent) {
      fs.writeFileSync(GENERATED_ASSETS_FILE, newContent, 'utf8');
      lastGeneratedContent = newContent;
      console.log('[MOMORA-WATCHER] 🔄 Kod tabani guncellendi! (' + pngFiles.length + ' gorsel: src/generatedAssets.js)');
    }
  } catch (err) {
    console.error('[MOMORA-WATCHER] Hata:', err.message);
  }
}

function parseJsonBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try { resolve(body ? JSON.parse(body) : {}); } catch (e) { reject(e); }
    });
    req.on('error', reject);
  });
}

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS, GET');
  res.setHeader('Access-Control-Allow-Headers', '*');
  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    return res.end();
  }

  // A. Sonraki Isi Getir (Next Job for Extension Worker)
  if (req.method === 'GET' && req.url === '/job/next') {
    const job = getNextJob();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    if (job) {
      console.log('[JOB-DISPATCH] 🚀 Bot icin is gonderildi:', job.filename);
      res.end(JSON.stringify({ status: 'job', job }));
    } else {
      res.end(JSON.stringify({ status: 'idle' }));
    }
    return;
  }

  // B. Is Durumu Guncelle (Job Status Update)
  if (req.method === 'POST' && req.url === '/job/status') {
    try {
      const data = await parseJsonBody(req);
      const updated = updateJobStatus(data.id || data.filename, data.status, data);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ success: updated }));
    } catch (e) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // C. Yeni Is Ekle (Add Job to Queue)
  if (req.method === 'POST' && req.url === '/job/add') {
    try {
      const data = await parseJsonBody(req);
      const jobsToAdd = Array.isArray(data.jobs) ? data.jobs : [data];
      const queueData = loadQueue();
      let added = 0;
      jobsToAdd.forEach(j => {
        if (!j.filename || !j.prompt) return;
        const exists = queueData.jobs.some(existing => existing.filename === j.filename);
        if (!exists) {
          queueData.jobs.push({
            id: 'job_' + Date.now() + '_' + Math.random().toString(36).substr(2, 5),
            filename: j.filename,
            prompt: j.prompt,
            transparent: j.transparent !== false,
            status: 'pending',
            attempts: 0,
            createdAt: Date.now()
          });
          added++;
        }
      });
      saveQueue(queueData);
      console.log('[JOB-ADD] ➕ ' + added + ' yeni gorsel kuyruga eklendi.');
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ success: true, added, total: queueData.jobs.length }));
    } catch (e) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // D. Kuyruk Listesi ve Istatistikleri (Get Queue List)
  if (req.method === 'GET' && req.url === '/job/list') {
    const queueData = loadQueue();
    const stats = {
      total: queueData.jobs.length,
      pending: queueData.jobs.filter(j => j.status === 'pending').length,
      processing: queueData.jobs.filter(j => j.status === 'processing').length,
      done: queueData.jobs.filter(j => j.status === 'done').length,
      error: queueData.jobs.filter(j => j.status === 'error').length
    };
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ stats, jobs: queueData.jobs }));
    return;
  }

  // 1. Mevcut Dosya Listesi Endpointi
  if (req.method === 'GET' && (req.url === '/list' || req.url.startsWith('/list?'))) {
    try {
      const allEntries = fs.readdirSync(ASSETS_DIR);
      const files = allEntries.filter(f => {
        try {
          return !fs.statSync(path.join(ASSETS_DIR, f)).isDirectory() && f.endsWith('.png');
        } catch (e) { return false; }
      });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ files }));
    } catch (e) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // 1b. 3D Model Listesi Endpointi
  if (req.method === 'GET' && req.url === '/models') {
    try {
      const allEntries = fs.readdirSync(ASSETS_DIR);
      const models = allEntries.filter(f => f.endsWith('.glb') || f.endsWith('.gltf'));
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ models }));
    } catch (e) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: e.message }));
    }
    return;
  }

  // 1c. 3D Fetus Viewer Sayfasi
  if (req.method === 'GET' && (req.url === '/3d' || req.url === '/viewer' || req.url === '/3d/')) {
    const viewerPath = path.join(__dirname, 'view_3d_fetus.html');
    if (fs.existsSync(viewerPath)) {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      fs.createReadStream(viewerPath).pipe(res);
      return;
    }
  }

  // 2. Asset Dosyasi Sunucu Endpointi
  if (req.method === 'GET' && req.url.startsWith('/assets/')) {
    const filename = decodeURIComponent(req.url.replace('/assets/', ''));
    const filePath = path.join(ASSETS_DIR, filename);
    if (fs.existsSync(filePath)) {
      const ext = path.extname(filename).toLowerCase();
      let contentType = 'application/octet-stream';
      if (ext === '.png') contentType = 'image/png';
      else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
      else if (ext === '.glb') contentType = 'model/gltf-binary';
      else if (ext === '.gltf') contentType = 'model/gltf+json';
      res.writeHead(200, { 'Content-Type': contentType });
      fs.createReadStream(filePath).pipe(res);
      return;
    } else {
      res.writeHead(404);
      res.end('Not found');
      return;
    }
  }

  // 3. Gorsel Yukleme Endpointi
  if (req.method === 'POST' && req.url.startsWith('/upload')) {
    const urlObj = new URL(req.url, 'http://localhost:' + PORT);
    const filename = urlObj.searchParams.get('filename') || ('image_' + Date.now() + '.png');
    const shouldMakeTransparent = urlObj.searchParams.get('transparent') !== 'false';
    const dest = path.join(ASSETS_DIR, filename);
    const writeStream = fs.createWriteStream(dest);
    req.pipe(writeStream);
    req.on('end', async () => {
      console.log('[ASSET-RECEIVER] 📥 Alindi: ' + filename + ' (Seffaf: ' + (shouldMakeTransparent ? 'EVET' : 'HAYIR') + ')');
      if (shouldMakeTransparent && !filename.endsWith('.glb')) {
        await makeTransparentPNG(dest);
      }
      updateGeneratedAssetsFile();
      updateJobStatus(filename, 'done', { thumb: '/assets/' + filename });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok', filename, transparent: shouldMakeTransparent }));
    });
    req.on('error', (err) => {
      console.error('[ASSET-RECEIVER] Hata:', err);
      res.writeHead(500);
      res.end(JSON.stringify({ error: err.message }));
    });
    return;
  }

  res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end('MOMORA Transparent Asset Receiver & Autonomous Job Engine calisiyor.');
});

server.listen(PORT, () => {
  console.log('[MOMORA] 🪄 Otomatik Seffaf PNG Alici ve Otonom Is Kuyrugu http://localhost:' + PORT + ' uzerinde hazir!');
  updateGeneratedAssetsFile();
  setInterval(updateGeneratedAssetsFile, 3000);
});