// Momora Kapsamli Bebek Isimleri Veritabani
// 65+ Zengin Bebek Ismi (Kiz, Erkek, Uniseks), Kokenler, Anlamlar ve Ortak Eslesme

export const babyNamesList = [
  {
    "id": "bn_defne",
    "name": "Defne",
    "gender": "Kız",
    "origin": "Yunanca / Akdeniz",
    "meaning": "Defnegillerden, yaprakları güzel kokulu ve yaz-kış yeşil kalan asil ağaç; zafer, barış ve zarafetin simgesi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_zeynep",
    "name": "Zeynep",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Babasının süsü, değerli mücevherler ve göz alıcı taşlar.",
    "quran": true,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_asel",
    "name": "Asel",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Cennetteki bal ırmağı, saf ve şifalı tatlılık.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_lina",
    "name": "Lina",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Cennetteki narin hurma fidesi, yumuşak huylu ve sevecen.",
    "quran": true,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_alara",
    "name": "Alara",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Eski Türk mitolojisinde su perisi, al renkli ırmak, ferahlık ve can veren.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_zumra",
    "name": "Zümra",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Güzel ahlaklı, cesur, zeki ve bilgili kadınlar topluluğu.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_elis",
    "name": "Elis",
    "gender": "Kız",
    "origin": "Türkçe / Evrensel",
    "meaning": "Güzel kokulu kır çiçeği, saf sevgi ve naiflik.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_doga",
    "name": "Doğa",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Canlı varlıklar bütünü, hayatın ve tazeliğin kaynağı.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_beren",
    "name": "Beren",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Güçlü, akıllı, zekasıyla parlayan dirayetli insan.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_masal",
    "name": "Masal",
    "gender": "Kız",
    "origin": "Arapça / Türkçe",
    "meaning": "Büyülü dünyaların ve saf sevginin zaferini anlatan efsanevi öykü.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_bade",
    "name": "Bade",
    "gender": "Kız",
    "origin": "Farsça",
    "meaning": "Aşk şerbeti, ilahi sevgi, kutsal ilham.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_miray",
    "name": "Miray",
    "gender": "Kız",
    "origin": "Farsça / Türkçe",
    "meaning": "Yılın ilk aylarında doğan, ay gibi ışıldayan kraliçe.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_derin",
    "name": "Derin",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Yüksek kavrayışlı, engin ve etkileyici duygu dünyası olan.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ipek",
    "name": "İpek",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Parlak, yumuşak ve değerli dokuma; incelik ve zarafet simgesi.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_nehir",
    "name": "Nehir",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Akıp giden berrak ırmak; bereket ve canlılık.",
    "quran": true,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_duru",
    "name": "Duru",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Bulanık olmayan, berrak, saf ve aydınlık.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_mercan",
    "name": "Mercan",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Deniz diplerinde yaşayan kırmızı kıymetli taş; cennet nimeti.",
    "quran": true,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_alya",
    "name": "Alya",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Yüksek yer, gökyüzü, zirve; yücelik ve asalet.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_hazel",
    "name": "Hazel",
    "gender": "Kelt / Evrensel",
    "meaning": "Fındık ağacı, bilgelik ve korunmanın sembolü.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_beliz",
    "name": "Beliz",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "İşaret, iz, alamet; hayata bırakılan kalıcı iz.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_ada",
    "name": "Ada",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Dört tarafı sularla çevrili kara parçası; huzur ve sığınak.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_nil",
    "name": "Nil",
    "gender": "Kız",
    "origin": "Mısır / Arapça",
    "meaning": "Dünyanın en bereketli nehri; mavi renk ve diriliş.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_sare",
    "name": "Sare",
    "gender": "Kız",
    "origin": "İbranice / Arapça",
    "meaning": "Saf, temiz, prenses ve soylu hanımefendi.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_inci",
    "name": "İnci",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "İstiridye içinde sabırla oluşan nadide parlak cevher.",
    "quran": true,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_eylul",
    "name": "Eylül",
    "gender": "Kız",
    "origin": "Süryanice / Arapça",
    "meaning": "Sonbaharın ilk ayı; dinginlik ve romantizm mevsimi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ruya",
    "name": "Rüya",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Uykuda görülen güzel düş; en tatlı dilek.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ece",
    "name": "Ece",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Kraliçe, hükümdar kadın, güzeller güzeli lider.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_verda",
    "name": "Verda",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Gül goncası, taze ve zarif çiçek.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_azra",
    "name": "Azra",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "El değmemiş kum tepesi, saf ve masum timsal.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_asli",
    "name": "Aslı",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Bir şeyin temeli, kökü, hakikati; Kerem ile Aslı destanının asil kahramanı.",
    "quran": false,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ilayda",
    "name": "İlayda",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Su perisi, ırmakların saf koruyucusu.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_dilara",
    "name": "Dilara",
    "gender": "Kız",
    "origin": "Farsça",
    "meaning": "Gönül çalan, kalbi dinlendiren, sevilen güzel sevgili.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_atlas",
    "name": "Atlas",
    "gender": "Erkek",
    "origin": "Mitoloji / Evrensel",
    "meaning": "Gökkubbeyi omuzlarında taşıyan güçlü figür; engin harita.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_alparslan",
    "name": "Alparslan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Cesur, korkusuz arslan; ulu Selçuklu fatihi.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_kerem",
    "name": "Kerem",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Soylu asalet, cömertlik, lütuf ve bağışlayıcılık.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_gokturk",
    "name": "Göktürk",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Göğe mensup Türk, bağımsızlık ruhu.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_metehan",
    "name": "Metehan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Büyük Hun kurucusu; disiplin ve cesaretin simgesi hakan.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_kaan",
    "name": "Kaan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Hanların hanı, hükümdar, mutlak lider.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_emir",
    "name": "Emir",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Bir kavmin başı, yönetici, kumandan ve prens.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_aras",
    "name": "Aras",
    "gender": "Erkek",
    "origin": "Türkçe / Farsça",
    "meaning": "Doğu Anadolu’da hızla akan ulu nehir; sahip çıkılan at yelesi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_toprak",
    "name": "Toprak",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Canlıları besleyen, bereketli, cömert yer kabuğu.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_cinar",
    "name": "Çınar",
    "gender": "Erkek",
    "origin": "Farsça",
    "meaning": "Yüzyıllarca yaşayan ulu, derin köklü bilge ağaç.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_yaman",
    "name": "Yaman",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Güçlü, becerikli, zorlukları aşan dirayetli insan.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_ruzgar",
    "name": "Rüzgar",
    "gender": "Erkek",
    "origin": "Farsça",
    "meaning": "Havanın hareketiyle oluşan ferah esinti; hız ve özgürlük.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_poyraz",
    "name": "Poyraz",
    "gender": "Erkek",
    "origin": "Yunanca / Türkçe",
    "meaning": "Kuzeydoğudan esen tazeleyici ve kuvvetli rüzgar.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_doruk",
    "name": "Doruk",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Dağların en yüksek zirvesi, başarıda en üst nokta.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_eymen",
    "name": "Eymen",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Uğurlu, bereketli, talihli; kutlu kimse.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ali",
    "name": "Ali",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Yüce, ulu, yüksek mertebeli; ilim ve cesaret timsali.",
    "quran": true,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_yigit",
    "name": "Yiğit",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Cesur, yürekli, mert, adaletten ayrılmayan alp.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ozan",
    "name": "Ozan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Şiir söyleyen halk şairi, saz çalan aşık, söz ustası.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_pamir",
    "name": "Pamir",
    "gender": "Erkek",
    "origin": "Türkçe / Farsça",
    "meaning": "Dünyanın Çatısı sayılan ulu sıradağlar.",
    "quran": false,
    "tag": "Özgün & Nadir",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_meric",
    "name": "Meriç",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Balkanlar’dan akıp gelen kadim ulu ırmak.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_pars",
    "name": "Pars",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Çevik, hızlı ve asil leopar.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_kayra",
    "name": "Kayra",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Eski Türk inancında göğün bahşettiği büyük lütuf ve iyilik.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ayaz",
    "name": "Ayaz",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Duru ve berrak kış gecesinde gökte yıldızlar parlarken serin esinti.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_barlas",
    "name": "Barlas",
    "gender": "Erkek",
    "origin": "Türkçe / Moğolca",
    "meaning": "Kahraman, savaşçı, soylu aileden gelen yiğit.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_selim",
    "name": "Selim",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Kusursuz, sağlıklı, doğru ve samimi kalpli.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_yagiz",
    "name": "Yağız",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Esmer, güçlü, dinç ve dayanıklı yiğit.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_tuna",
    "name": "Tuna",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Görkemli ulu nehir; bol su ve coşku.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_barin",
    "name": "Barın",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Bütün, hep, güç ve kuvvet simgesi tarihi Türk boyu.",
    "quran": false,
    "tag": "Özgün & Nadir",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_deniz",
    "name": "Deniz",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Yeryüzünü saran engin mavi sular; sonsuz özgürlük ve ferahlık.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_arya",
    "name": "Arya",
    "gender": "Üniseks",
    "origin": "Sanskritçe / İtalyanca",
    "meaning": "Soylu, erdemli; operada bestelenmiş büyüleyici ezgi.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_evren",
    "name": "Evren",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Sonsuz kainat; mitolojide koruyucu ulu varlık.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_umut",
    "name": "Umut",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Geleceğe dair beslenen güzel beklenti ve içsel inanç.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_ilgaz",
    "name": "Ilgaz",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Anadolu’nun çam kokulu ulu dağı; heybet ve duruluk.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_yagmur",
    "name": "Yağmur",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Bulutlardan damlayan hayat suyu, toprağa can veren bereket.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_gunes",
    "name": "Güneş",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Dünyayı ısıtan en parlak gök cismi; hayat ve neşenin kaynağı.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_ege",
    "name": "Ege",
    "gender": "Üniseks",
    "origin": "Türkçe / Yunanca",
    "meaning": "Zeytin kokulu masmavi deniz; bir çocuğu koruyan bilge rehber.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_bilge",
    "name": "Bilge",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Derin kavrayışlı, adil ve tecrübeli ulu insan.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_cagri",
    "name": "Çağrı",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Davet, sesleniş, haber; asil doğan kuşu.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_baris",
    "name": "Barış",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Huzur, uzlaşma, sevgi dolu dünya ideali.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_eren",
    "name": "Eren",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Ermiş, olgun, gönül gözü açık hakikat yolcusu.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_utku",
    "name": "Utku",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Emek ve mücadele sonunda kazanılan asil zafer.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_mira",
    "name": "Mira",
    "gender": "Üniseks",
    "origin": "Latince / Sanskritçe",
    "meaning": "Parlayan yıldız; okyanus ve barış.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  }
];

export const nameOrigins = ['Tümü', 'Türkçe', 'Arapça', 'Farsça', 'Evrensel'];
export const nameThemes = ['Tümü', '💕 Ortak Eşleşmeler', '🌿 Doğa & Çiçek', '🏛️ Tarihi & Göktürk', '✨ Modern & Kısa', '📖 Kuran\'da Geçen'];
