// Momora Kapsamli Bebek Isimleri Veritabani
// 9000+ Zengin Bebek Ismi (Kiz, Erkek, Uniseks), Kokenler, Anlamlar ve Ortak Eslesme
import { babyNamesCatalog } from './babyNamesCatalog.js';

const initialBabyNames = [
  {
    "id": "bn_defne",
    "name": "Defne",
    "gender": "Kız",
    "origin": "Yunanca / Akdeniz",
    "meaning": "Defnegillerden, yaprakları güzel kokulu ve yaz-kış yeşil kalan asil ağaç; zafer, barış ve zarafetin simgesi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_zeynep",
    "name": "Zeynep",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Babasının süsü, değerli mücevherler ve göz alıcı taşlar.",
    "quran": true,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_asel",
    "name": "Asel",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Cennetteki bal ırmağı, saf ve şifalı tatlılık.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_lina",
    "name": "Lina",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Cennetteki narin hurma fidesi, yumuşak huylu ve sevecen.",
    "quran": true,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_alara",
    "name": "Alara",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Eski Türk mitolojisinde su perisi, al renkli ırmak, ferahlık ve can veren.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_zumra",
    "name": "Zümra",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Güzel ahlaklı, cesur, zeki ve bilgili kadınlar topluluğu.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_elis",
    "name": "Elis",
    "gender": "Kız",
    "origin": "Türkçe / Evrensel",
    "meaning": "Güzel kokulu kır çiçeği, saf sevgi ve naiflik.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_doga",
    "name": "Doğa",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Canlı varlıklar bütünü, hayatın ve tazeliğin kaynağı.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_beren",
    "name": "Beren",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Güçlü, akıllı, zekasıyla parlayan dirayetli insan.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_masal",
    "name": "Masal",
    "gender": "Kız",
    "origin": "Arapça / Türkçe",
    "meaning": "Büyülü dünyaların ve saf sevginin zaferini anlatan efsanevi öykü.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_bade",
    "name": "Bade",
    "gender": "Kız",
    "origin": "Farsça",
    "meaning": "Aşk şerbeti, ilahi sevgi, kutsal ilham.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_miray",
    "name": "Miray",
    "gender": "Kız",
    "origin": "Farsça / Türkçe",
    "meaning": "Yılın ilk aylarında doğan, ay gibi ışıldayan kraliçe.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_derin",
    "name": "Derin",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Yüksek kavrayışlı, engin ve etkileyici duygu dünyası olan.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ipek",
    "name": "İpek",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Parlak, yumuşak ve değerli dokuma; incelik ve zarafet simgesi.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_nehir",
    "name": "Nehir",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Akıp giden berrak ırmak; bereket ve canlılık.",
    "quran": true,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_duru",
    "name": "Duru",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Bulanık olmayan, berrak, saf ve aydınlık.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_mercan",
    "name": "Mercan",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Deniz diplerinde yaşayan kırmızı kıymetli taş; cennet nimeti.",
    "quran": true,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_alya",
    "name": "Alya",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Yüksek yer, gökyüzü, zirve; yücelik ve asalet.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_hazel",
    "name": "Hazel",
    "gender": "Kelt / Evrensel",
    "meaning": "Fındık ağacı, bilgelik ve korunmanın sembolü.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_beliz",
    "name": "Beliz",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "İşaret, iz, alamet; hayata bırakılan kalıcı iz.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_ada",
    "name": "Ada",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Dört tarafı sularla çevrili kara parçası; huzur ve sığınak.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_nil",
    "name": "Nil",
    "gender": "Kız",
    "origin": "Mısır / Arapça",
    "meaning": "Dünyanın en bereketli nehri; mavi renk ve diriliş.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_sare",
    "name": "Sare",
    "gender": "Kız",
    "origin": "İbranice / Arapça",
    "meaning": "Saf, temiz, prenses ve soylu hanımefendi.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_inci",
    "name": "İnci",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "İstiridye içinde sabırla oluşan nadide parlak cevher.",
    "quran": true,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_eylul",
    "name": "Eylül",
    "gender": "Kız",
    "origin": "Süryanice / Arapça",
    "meaning": "Sonbaharın ilk ayı; dinginlik ve romantizm mevsimi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ruya",
    "name": "Rüya",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Uykuda görülen güzel düş; en tatlı dilek.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ece",
    "name": "Ece",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Kraliçe, hükümdar kadın, güzeller güzeli lider.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_verda",
    "name": "Verda",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Gül goncası, taze ve zarif çiçek.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_azra",
    "name": "Azra",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "El değmemiş kum tepesi, saf ve masum timsal.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_asli",
    "name": "Aslı",
    "gender": "Kız",
    "origin": "Arapça",
    "meaning": "Bir şeyin temeli, kökü, hakikati; Kerem ile Aslı destanının asil kahramanı.",
    "quran": false,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ilayda",
    "name": "İlayda",
    "gender": "Kız",
    "origin": "Türkçe",
    "meaning": "Su perisi, ırmakların saf koruyucusu.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_dilara",
    "name": "Dilara",
    "gender": "Kız",
    "origin": "Farsça",
    "meaning": "Gönül çalan, kalbi dinlendiren, sevilen güzel sevgili.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_atlas",
    "name": "Atlas",
    "gender": "Erkek",
    "origin": "Mitoloji / Evrensel",
    "meaning": "Gökkubbeyi omuzlarında taşıyan güçlü figür; engin harita.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_alparslan",
    "name": "Alparslan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Cesur, korkusuz arslan; ulu Selçuklu fatihi.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_kerem",
    "name": "Kerem",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Soylu asalet, cömertlik, lütuf ve bağışlayıcılık.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_gokturk",
    "name": "Göktürk",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Göğe mensup Türk, bağımsızlık ruhu.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_metehan",
    "name": "Metehan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Büyük Hun kurucusu; disiplin ve cesaretin simgesi hakan.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_kaan",
    "name": "Kaan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Hanların hanı, hükümdar, mutlak lider.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_emir",
    "name": "Emir",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Bir kavmin başı, yönetici, kumandan ve prens.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_aras",
    "name": "Aras",
    "gender": "Erkek",
    "origin": "Türkçe / Farsça",
    "meaning": "Doğu Anadolu’da hızla akan ulu nehir; sahip çıkılan at yelesi.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_toprak",
    "name": "Toprak",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Canlıları besleyen, bereketli, cömert yer kabuğu.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_cinar",
    "name": "Çınar",
    "gender": "Erkek",
    "origin": "Farsça",
    "meaning": "Yüzyıllarca yaşayan ulu, derin köklü bilge ağaç.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_yaman",
    "name": "Yaman",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Güçlü, becerikli, zorlukları aşan dirayetli insan.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_ruzgar",
    "name": "Rüzgar",
    "gender": "Erkek",
    "origin": "Farsça",
    "meaning": "Havanın hareketiyle oluşan ferah esinti; hız ve özgürlük.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_poyraz",
    "name": "Poyraz",
    "gender": "Erkek",
    "origin": "Yunanca / Türkçe",
    "meaning": "Kuzeydoğudan esen tazeleyici ve kuvvetli rüzgar.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_doruk",
    "name": "Doruk",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Dağların en yüksek zirvesi, başarıda en üst nokta.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_eymen",
    "name": "Eymen",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Uğurlu, bereketli, talihli; kutlu kimse.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ali",
    "name": "Ali",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Yüce, ulu, yüksek mertebeli; ilim ve cesaret timsali.",
    "quran": true,
    "tag": "Zamansız Klasik",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_yigit",
    "name": "Yiğit",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Cesur, yürekli, mert, adaletten ayrılmayan alp.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_ozan",
    "name": "Ozan",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Şiir söyleyen halk şairi, saz çalan aşık, söz ustası.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_pamir",
    "name": "Pamir",
    "gender": "Erkek",
    "origin": "Türkçe / Farsça",
    "meaning": "Dünyanın Çatısı sayılan ulu sıradağlar.",
    "quran": false,
    "tag": "Özgün & Nadir",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_meric",
    "name": "Meriç",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Balkanlar’dan akıp gelen kadim ulu ırmak.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_pars",
    "name": "Pars",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Çevik, hızlı ve asil leopar.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_kayra",
    "name": "Kayra",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Eski Türk inancında göğün bahşettiği büyük lütuf ve iyilik.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_ayaz",
    "name": "Ayaz",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Duru ve berrak kış gecesinde gökte yıldızlar parlarken serin esinti.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_barlas",
    "name": "Barlas",
    "gender": "Erkek",
    "origin": "Türkçe / Moğolca",
    "meaning": "Kahraman, savaşçı, soylu aileden gelen yiğit.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_selim",
    "name": "Selim",
    "gender": "Erkek",
    "origin": "Arapça",
    "meaning": "Kusursuz, sağlıklı, doğru ve samimi kalpli.",
    "quran": true,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_yagiz",
    "name": "Yağız",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Esmer, güçlü, dinç ve dayanıklı yiğit.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_tuna",
    "name": "Tuna",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Görkemli ulu nehir; bol su ve coşku.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_barin",
    "name": "Barın",
    "gender": "Erkek",
    "origin": "Türkçe",
    "meaning": "Bütün, hep, güç ve kuvvet simgesi tarihi Türk boyu.",
    "quran": false,
    "tag": "Özgün & Nadir",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_deniz",
    "name": "Deniz",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Yeryüzünü saran engin mavi sular; sonsuz özgürlük ve ferahlık.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_arya",
    "name": "Arya",
    "gender": "Üniseks",
    "origin": "Sanskritçe / İtalyanca",
    "meaning": "Soylu, erdemli; operada bestelenmiş büyüleyici ezgi.",
    "quran": false,
    "tag": "Zarafet & Sanat",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_evren",
    "name": "Evren",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Sonsuz kainat; mitolojide koruyucu ulu varlık.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_umut",
    "name": "Umut",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Geleceğe dair beslenen güzel beklenti ve içsel inanç.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Zamansız Klasik",
    "partnerMatch": true
  },
  {
    "id": "bn_ilgaz",
    "name": "Ilgaz",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Anadolu’nun çam kokulu ulu dağı; heybet ve duruluk.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Özgün & Nadir",
    "partnerMatch": false
  },
  {
    "id": "bn_yagmur",
    "name": "Yağmur",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Bulutlardan damlayan hayat suyu, toprağa can veren bereket.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_gunes",
    "name": "Güneş",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Dünyayı ısıtan en parlak gök cismi; hayat ve neşenin kaynağı.",
    "quran": false,
    "tag": "Doğa & Çiçek",
    "popularity": "Trend 2026",
    "partnerMatch": true
  },
  {
    "id": "bn_ege",
    "name": "Ege",
    "gender": "Üniseks",
    "origin": "Türkçe / Yunanca",
    "meaning": "Zeytin kokulu masmavi deniz; bir çocuğu koruyan bilge rehber.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": false
  },
  {
    "id": "bn_bilge",
    "name": "Bilge",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Derin kavrayışlı, adil ve tecrübeli ulu insan.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_cagri",
    "name": "Çağrı",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Davet, sesleniş, haber; asil doğan kuşu.",
    "quran": false,
    "tag": "Tarihi & Göktürk",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_baris",
    "name": "Barış",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Huzur, uzlaşma, sevgi dolu dünya ideali.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_eren",
    "name": "Eren",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Ermiş, olgun, gönül gözü açık hakikat yolcusu.",
    "quran": false,
    "tag": "Manevi & Dini",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_utku",
    "name": "Utku",
    "gender": "Üniseks",
    "origin": "Türkçe",
    "meaning": "Emek ve mücadele sonunda kazanılan asil zafer.",
    "quran": false,
    "tag": "Güç & Asalet",
    "popularity": "Zamansız Klasik",
    "partnerMatch": false
  },
  {
    "id": "bn_mira",
    "name": "Mira",
    "gender": "Üniseks",
    "origin": "Latince / Sanskritçe",
    "meaning": "Parlayan yıldız; okyanus ve barış.",
    "quran": false,
    "tag": "Modern & Kısa",
    "popularity": "Trend 2026",
    "partnerMatch": true
  }
];

const initialSet = new Set(initialBabyNames.map(n => n.name.toLowerCase()));
const extraFromCatalog = (babyNamesCatalog || []).filter(n => !initialSet.has(n.name.toLowerCase()));

export const babyNamesList = [...initialBabyNames, ...extraFromCatalog];

export const nameThemes = [
  'Tümü',
  'Ortak Eşleşmeler',
  'Doğa & Çiçek',
  'Tarihi & Göktürk',
  'Modern & Kısa',
  "Kuran'da Geçen",
  'Güç & Asalet',
  'Zarafet & Sanat',
  'Özgün & Nadir',
  'Zamansız Klasik',
];

const tagMapEn = {
  'Doğa & Çiçek': 'Nature & Floral',
  'Zamansız Klasik': 'Timeless Classic',
  'Manevi & Dini': 'Spiritual & Traditional',
  'Modern & Kısa': 'Modern & Short',
  'Tarihi & Göktürk': 'Historical & Epic',
  'Güç & Asalet': 'Strength & Nobility',
  'Zarafet & Sanat': 'Grace & Art',
  'Özgün & Nadir': 'Unique & Rare',
};

const popMapEn = {
  'Trend 2026': 'Trending 2026',
  'Zamansız Klasik': 'Timeless Classic',
  'Özgün & Nadir': 'Unique & Rare',
};

const originMapEn = {
  'Yunanca / Akdeniz': 'Greek / Mediterranean',
  'Arapça': 'Arabic',
  'Türkçe': 'Turkish',
  'Türkçe / Evrensel': 'Turkish / Universal',
  'Arapça / Türkçe': 'Arabic / Turkish',
  'Farsça': 'Persian',
  'Farsça / Türkçe': 'Persian / Turkish',
  'Mısır / Arapça': 'Egyptian / Arabic',
  'İbranice / Arapça': 'Hebrew / Arabic',
  'Süryanice / Arapça': 'Syriac / Arabic',
  'Mitoloji / Evrensel': 'Mythology / Universal',
  'Türkçe / Farsça': 'Turkish / Persian',
  'Yunanca / Türkçe': 'Greek / Turkish',
  'Türkçe / Moğolca': 'Turkish / Mongolian',
  'Sanskritçe / İtalyanca': 'Sanskrit / Italian',
  'Türkçe / Yunanca': 'Turkish / Greek',
  'Latince / Sanskritçe': 'Latin / Sanskrit',
};

const meaningsEn = {
  bn_defne: 'Noble laurel tree with fragrant leaves evergreen in summer and winter; symbol of victory, peace, and grace.',
  bn_zeynep: "Father's precious ornament, rare jewels and radiant gemstones.",
  bn_asel: 'Stream of pure honey in paradise; wholesome, soothing, and sweet.',
  bn_lina: 'Delicate palm seedling in paradise; tenderhearted, gentle, and loving.',
  bn_alara: 'Water nymph in ancient Turkic mythology; crimson river bringing freshness and vitality.',
  bn_zumra: 'Intelligent, courageous, and noble-spirited woman; also emerald beauty.',
  bn_elis: 'Fragrant flower scent spreading in the air; pure and graceful.',
  bn_doga: 'Nature itself, encompassing all natural beauty, life, and green vitality.',
  bn_beren: 'Intelligent, quick-witted, talented, and courageous.',
  bn_masal: 'Enchanting fairytale; world filled with imagination, wonders, and sweet dreams.',
  bn_bade: 'Pure essence of love and devotion; radiant and sincere.',
  bn_miray: 'Radiant like the moon; shining leader who brightens the world.',
  bn_derin: 'Profound intellect, bottomless wisdom, and emotional depth.',
  bn_ipek: 'Silken softness, delicate grace, and timeless nobility.',
  bn_nehir: 'Vibrant river flowing steadily towards the sea; life and serenity.',
  bn_duru: 'Crystal clear, transparent, and pure spirit.',
  bn_mercan: 'Vibrant coral gemstone from the deep seas; protection and precious beauty.',
  bn_alya: 'Highest peak of the skies, heavenly nobility and grandeur.',
  bn_hazel: 'Autumn tree leaves; calm, wisdom, and warm beauty.',
  bn_beliz: 'Clear sign, distinct mark, and memorable footprint.',
  bn_ada: 'Peaceful island surrounded by clear waters; safe haven and uniqueness.',
  bn_nil: 'Life-giving, majestic river bringing fertility and abundance.',
  bn_sare: 'Pure, distinguished lady; beloved and sincere.',
  bn_inci: 'Precious pearl formed with patience inside the oyster; rare grace.',
  bn_eylul: 'Gentle autumn breeze; romance, peace, and serenity.',
  bn_ruya: 'Beautiful dream, visionary imagination, and cherished desire.',
  bn_ece: 'Beloved queen, graceful and esteemed ruler.',
  bn_verda: 'Fresh morning dew and blooming rose petals.',
  bn_azra: 'Pure, untouched pearl; symbol of maiden innocence and brilliance.',
  bn_asli: 'Authentic, rooted, and noble essence; legendary enduring love.',
  bn_ilayda: 'Enchanting water fairy, life of clear streams and springs.',
  bn_dilara: 'Heart-soothing and charming sweetheart; source of joy.',
  bn_atlas: 'Vast heavens, bearer of the skies; world atlas and celestial strength.',
  bn_alparslan: 'Brave, legendary lion; symbol of courage and heroic leadership.',
  bn_kerem: 'Generosity, noble benevolence, and magnanimous kindness.',
  bn_gokturk: 'Noble sky nomads; legendary ancient Turkic roots and heritage.',
  bn_metehan: 'Legendary emperor of the Great Steppe; founder of military order.',
  bn_kaan: 'Ruler of rulers, grand sovereign, and dignified king.',
  bn_emir: 'Commanding prince, leader with innate authority.',
  bn_aras: 'Mighty river cutting through great mountains; unstoppable force.',
  bn_toprak: 'Generous earth; fertile mother soil giving life to all.',
  bn_cinar: 'Majestic plane tree standing for centuries; shade, wisdom, and endurance.',
  bn_yaman: 'Resourceful, determined, courageous, and capable.',
  bn_ruzgar: 'Fresh breeze, free-spirited wind carrying autumn scents.',
  bn_poyraz: 'Invigorating north-east wind; freshness and lively energy.',
  bn_doruk: 'Highest mountain summit, pinnacle of achievement and vision.',
  bn_eymen: 'Blessed, fortunate, safe, and right-handed virtue.',
  bn_ali: 'Exalted, honorable, and occupying the highest moral station.',
  bn_yigit: 'Fearless hero, brave warrior of exceptional character.',
  bn_ozan: 'Poetic bard, master of words, storyteller and musical soul.',
  bn_pamir: 'Roof of the world, grand snow-capped peaks reaching the stars.',
  bn_meric: 'Majestic river connecting lands; life-giving and calm.',
  bn_pars: 'Swift, agile leopard; nobility and sharp perception.',
  bn_kayra: 'Divine grace, sovereign benevolence, and heavenly gift.',
  bn_ayaz: 'Crisp, crystal-clear starlit winter frost; sharp and pure.',
  bn_barlas: 'Valiant warrior, steadfast protector, and fearless leader.',
  bn_selim: 'Peaceful, sound-minded, gentle, and free of malice.',
  bn_yagiz: 'Stalwart, handsome, strong, and noble-hearted youth.',
  bn_tuna: 'Majestic blue river flowing through continents; wealth and life.',
  bn_barin: 'Unshakeable strength, all-embracing peace, and quiet power.',
  bn_deniz: 'Vast ocean, freedom, endless horizon, and deep wisdom.',
  bn_arya: 'Operatic melody, noble spirit, and poetic harmony.',
  bn_evren: 'The vast cosmos, eternity, and all-encompassing harmony.',
  bn_umut: 'Eternal hope, morning light, and inspiring optimism.',
  bn_ilgaz: 'Snowy evergreen mountain pine; fresh air and enduring spirit.',
  bn_yagmur: 'Life-giving gentle rain showers; fertility and peaceful fragrance.',
  bn_gunes: 'Golden sun, warmth, vital energy, and guiding light.',
  bn_ege: 'Turquoise Aegean breeze, warmth, olive branches, and hospitality.',
  bn_bilge: 'Wise sage, deep knowledge, understanding, and guiding mind.',
  bn_cagri: 'Noble call, invitation to unity, and welcoming proclamation.',
  bn_baris: 'Harmonious peace, reconciliation, and tranquil stillness.',
  bn_eren: 'Enlightened soul, spiritual wisdom, and saintly friend.',
  bn_utku: 'Noble victory achieved through devotion and righteous effort.',
  bn_mira: 'Shining celestial star; also ocean, wonder, and harmony.',
};

export function getLocalizedBabyName(nameObj, lang = 'tr') {
  if (!nameObj) return nameObj;
  if (lang !== 'en') return nameObj;
  return {
    ...nameObj,
    meaning: meaningsEn[nameObj.id] || nameObj.meaning,
    origin: originMapEn[nameObj.origin] || nameObj.origin,
    tag: tagMapEn[nameObj.tag] || nameObj.tag,
    popularity: popMapEn[nameObj.popularity] || nameObj.popularity,
    gender: nameObj.gender === 'Kız' ? 'Girl' : nameObj.gender === 'Erkek' ? 'Boy' : 'Unisex',
  };
}
