// AUTO-GENERATED BY MOMORA ASSET PIPELINE
// Bu dosya yeni görseller indirildikçe otomatik olarak güncellenir.

export const generatedAssets = {
  'baby': require('../assets/baby.png'),
  'banner_next_sleep': require('../assets/banner_next_sleep.png'),
  'bottle': require('../assets/bottle.png'),
  'btn_bottle': require('../assets/btn_bottle.png'),
  'btn_breast_pump': require('../assets/btn_breast_pump.png'),
  'btn_diaper': require('../assets/btn_diaper.png'),
  'btn_growth_tape': require('../assets/btn_growth_tape.png'),
  'btn_nursing': require('../assets/btn_nursing.png'),
  'btn_sleep': require('../assets/btn_sleep.png'),
  'btn_teething': require('../assets/btn_teething.png'),
  'btn_thermometer': require('../assets/btn_thermometer.png'),
  'btn_tummy_time': require('../assets/btn_tummy_time.png'),
  'card_appointment': require('../assets/card_appointment.png'),
  'card_ask_doctor': require('../assets/card_ask_doctor.png'),
  'card_blood_pressure': require('../assets/card_blood_pressure.png'),
  'card_contractions': require('../assets/card_contractions.png'),
  'card_health_report': require('../assets/card_health_report.png'),
  'card_hospital_bag': require('../assets/card_hospital_bag.png'),
  'card_kick_counter': require('../assets/card_kick_counter.png'),
  'card_scale': require('../assets/card_scale.png'),
  'card_ultrasound_frame': require('../assets/card_ultrasound_frame.png'),
  'card_vitamin': require('../assets/card_vitamin.png'),
  'card_water': require('../assets/card_water.png'),
  'cat_bath': require('../assets/cat_bath.png'),
  'cat_bowl': require('../assets/cat_bowl.png'),
  'cat_diaper': require('../assets/cat_diaper.png'),
  'cat_wipes': require('../assets/cat_wipes.png'),
  'fetus': require('../assets/fetus.png'),
  'fruit_blueberry': require('../assets/fruit_blueberry.png'),
  'fruit_fig': require('../assets/fruit_fig.png'),
  'fruit_grape': require('../assets/fruit_grape.png'),
  'fruit_kumquat': require('../assets/fruit_kumquat.png'),
  'fruit_pea': require('../assets/fruit_pea.png'),
  'fruit_raspberry': require('../assets/fruit_raspberry.png'),
  'fruit_seed': require('../assets/fruit_seed.png'),
  'mother-baby': require('../assets/mother-baby.png'),
  'nursing': require('../assets/nursing.png'),
  'pregnancy': require('../assets/pregnancy.png'),
  'prod_baby_food': require('../assets/prod_baby_food.png'),
  'sleep': require('../assets/sleep.png'),
};

export function getAsset(name) {
  return generatedAssets[name] || null;
}
