import React, {useState, useRef, useEffect} from 'react';
import { View, Image, ScrollView, StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { T, Tap, Card, Page, Section, Progress } from './ui';
import { Icon, FruitArt } from './Icons';
import { colors } from './theme';
import { generatedAssets } from './generatedAssets';
import { Header, Button, Chips, Field, Empty, Hint, RowLink, SourceLink, f } from './FlowUI';
import { articles, topics, articleById, weeklyArticles } from './content';
import { getWeekInfo, formatLength, formatWeight, trimesterLabel } from './weekData';
import { normalizeSearch, pregnancyAt, uid, localDay } from './domain.mjs';

export function ArticleRow({article,onPress,read}) {return <Tap label={article.title} onPress={onPress} style={r.articleRow}><Image source={generatedAssets[article.image]} style={r.thumb}/><View style={{flex:1,gap:6}}><T style={f.label}>{topics.find(t=>t.id===article.topic)?.title.toLocaleUpperCase('tr')}</T><T bold style={{fontSize:15,lineHeight:21}}>{article.title}</T><T style={f.meta}>{article.minutes} dk okuma{read?' · Okundu':''}</T></View><Icon name="chevron" size={16} color={colors.purple}/></Tap>;}
export function ReadingRail({week,navigate,state}) {return <View><Section title="Bu haftana eşlik etsin" action="Tüm yazılar" onPress={()=>navigate('library')}/>{weeklyArticles(week).slice(0,2).map(article=><ArticleRow key={article.id} article={article} read={state.readArticles.includes(article.id)} onPress={()=>navigate('article',{id:article.id})}/>)}</View>;}
export function Library({state,navigate,back,data={}}) {
  const [query,setQuery]=useState('');const [topic,setTopic]=useState(data.topic||'all');const [tab,setTab]=useState(data.saved?'saved':'all');
  const shown=articles.filter(a=>(topic==='all'||a.topic===topic)&&(tab!=='saved'||state.savedArticles.includes(a.id))&&normalizeSearch(`${a.title} ${a.subtitle} ${topics.find(t=>t.id===a.topic)?.title}`).includes(normalizeSearch(query)));
  return <Page><Header title="Keşfet" subtitle="Merak ettiklerine, kendi hızında." back={back}/><Field label="İçerik ara" value={query} onChangeText={setQuery} placeholder="Örn. hareket, doğum, günlük"/>
    <Chips items={[{id:'all',title:'Sana özel'},{id:'saved',title:`Kaydettiklerin (${state.savedArticles.length})`}]} value={tab} onChange={setTab}/>
    {!query&&topic==='all'&&tab==='all'&&<><Tap label="Doğuma hazırlık konusunu keşfet" onPress={()=>setTopic('birth')} style={r.cover}><Image source={generatedAssets.blog_hospital_bag_pack} style={StyleSheet.absoluteFill}/><LinearGradient colors={['transparent','#30212AE6']} style={StyleSheet.absoluteFill}/><View style={r.coverCopy}><T style={{color:'#F0DEE6',fontSize:11,letterSpacing:2}}>BİRLİKTE HAZIRLANALIM</T><T bold style={{color:'white',fontSize:25,lineHeight:30}}>Büyük güne,{ '\n' }küçük adımlarla.</T><T style={{color:'white',fontSize:13}}>Doğuma hazırlık rehberleri  →</T></View></Tap>
    <Section title="Neyi merak ediyorsun?"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{topics.map(t=><Tap key={t.id} label={`${t.title} konusunu aç`} onPress={()=>setTopic(t.id)} style={r.topic}><Image source={generatedAssets[t.image]} style={r.topicImage}/><T bold style={{fontSize:14,marginTop:9}}>{t.title}</T><T style={f.meta}>{articles.filter(a=>a.topic===t.id).length} rehber</T></Tap>)}</ScrollView></>}
    <Chips items={[{id:'all',title:'Tüm konular'},...topics]} value={topic} onChange={setTopic}/>
    <T style={f.meta}>{shown.length} rehber{query?` · “${query}”`:''}</T>
    {shown.length?shown.map(a=><ArticleRow key={a.id} article={a} read={state.readArticles.includes(a.id)} onPress={()=>navigate('article',{id:a.id})}/>):<Empty title={tab==='saved'?'Burada sana ait bir kitaplık olacak':'Aradığını bulamadık'} text={tab==='saved'?'Yazılardaki kaydet düğmesine dokun. Seçtiğin konuya ait kayıtlar burada görünür.':'Daha kısa bir kelime deneyebilir veya konu filtresini kaldırabilirsin.'} action="Tüm rehberleri göster" onPress={()=>{setQuery('');setTopic('all');setTab('all');}}/>}
  </Page>;
}
export function ArticleDetail({data,state,update,navigate,back,toast}) {
  const a=articleById(data.id);const [large,setLarge]=useState(false);const [progress,setProgress]=useState(0);
  if(!a)return <Page><Header title="Yazı bulunamadı" back={back}/><Empty title="Bu içerik burada değil" text="Diğer rehberlere göz atabilirsin." action="Keşfet'e dön" onPress={()=>navigate('library')}/></Page>;
  const saved=state.savedArticles.includes(a.id),read=state.readArticles.includes(a.id);
  return <Page onScroll={event=>{const {contentOffset,contentSize,layoutMeasurement}=event.nativeEvent;setProgress(Math.min(100,contentOffset.y/Math.max(1,contentSize.height-layoutMeasurement.height)*100));}} scrollEventThrottle={80}>
    <Header title="Okuma köşesi" back={back} action={<Tap label={saved?'Yazıyı kaydedilenlerden çıkar':'Yazıyı kaydet'} onPress={()=>update(old=>({savedArticles:saved?old.savedArticles.filter(id=>id!==a.id):[...old.savedArticles,a.id]}))} style={f.iconButton}><Icon name={saved?'check':'book'} color={colors.purple}/></Tap>}/>
    <Progress value={progress} color={colors.purple} style={{height:3}}/><Image source={generatedAssets[a.image]} style={r.articleCover}/>
    <View style={{gap:10}}><T style={f.label}>{topics.find(t=>t.id===a.topic)?.title.toLocaleUpperCase('tr')}</T><T bold style={{fontSize:27,lineHeight:34}}>{a.title}</T><T style={f.body}>{a.subtitle}</T><View style={[f.row,{justifyContent:'space-between'}]}><T style={f.meta}>Momora rehberi · {a.minutes} dk</T><Tap label="Yazı boyutunu değiştir" onPress={()=>setLarge(!large)} style={f.iconButton}><T bold style={{fontSize:large?21:16}}>Aa</T></Tap></View></View>
    {a.sections.map((section,i)=><View key={section.title} style={{gap:9,paddingVertical:10}}><T style={f.label}>0{i+1}</T><T bold style={{fontSize:large?23:20,lineHeight:28}}>{section.title}</T><T style={[f.body,{fontSize:large?19:16,lineHeight:large?31:27}]}>{section.text}</T></View>)}
    {a.source&&<Card><T bold style={{fontSize:13}}>Kaynak ve içerik notu</T><T style={[f.meta,{marginTop:6}]}>Genel bilgilendirme amaçlıdır; kişisel sağlık önerisi yerine geçmez. Kaynak kontrolü: 12 Eylül 2026.</T><SourceLink source={a.source} onError={toast}/></Card>}
    {a.action&&<Button onPress={()=>navigate(a.action.route,a.action.data)}>{a.action.label} →</Button>}
    <Button secondary onPress={()=>{update(old=>({readArticles:read?old.readArticles.filter(id=>id!==a.id):[...old.readArticles,a.id]}));toast(read?'Okundu işareti kaldırıldı':'Okuma tamamlandı');}}>{read?'Okundu ✓ · İşareti kaldır':'Okudum'}</Button>
    <Section title="Buradan devam edebilirsin"/>{articles.filter(other=>other.id!==a.id&&other.topic===a.topic).slice(0,2).map(other=><ArticleRow key={other.id} article={other} onPress={()=>navigate('article',{id:other.id})}/>)}
  </Page>;
}
export function WeekStrip({week,onChange}) {
  const ref=useRef(null);useEffect(()=>{ref.current?.scrollTo({x:Math.max(0,(week-6)*52),animated:false});},[week]);
  return <ScrollView ref={ref} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:6,paddingVertical:8}} style={{flexGrow:0}}>{Array.from({length:37},(_,i)=>i+4).map(w=><Tap key={w} label={`${w}. haftayı incele`} accessibilityState={{selected:week===w}} onPress={()=>onChange(w)} style={[r.week,week===w&&{backgroundColor:colors.purple}]}><T bold={week===w} style={{color:week===w?'white':colors.ink}}>{w}</T><T style={{fontSize:9,color:week===w?'white':colors.muted}}>HAFTA</T></Tap>)}</ScrollView>;
}
export function WeekDetail({data={},state,update,navigate,back,toast,measure=false}) {
  const actual=pregnancyAt(state).week;const [week,setWeek]=useState(data.week||actual);const [section,setSection]=useState('baby');const [note,setNote]=useState('');const info=getWeekInfo(week);
  const notes=state.journal.filter(n=>n.week===week);
  return <Page><Header title={measure?'Ölçü rehberi':'Bu hafta ikiniz'} subtitle={`${week}. hafta · ${trimesterLabel(info.trimester)}`} back={back}/><WeekStrip week={week} onChange={setWeek}/>
    {week!==actual&&<View style={[f.row,{justifyContent:'space-between'}]}><T style={f.meta}>Şu an {week}. haftayı inceliyorsun.</T><Tap onPress={()=>setWeek(actual)} label="Kendi haftama dön" style={{padding:8,minHeight:44,justifyContent:'center'}}><T bold style={{fontSize:12,color:colors.purple}}>Benim haftam</T></Tap></View>}
    <View style={r.fruitStage}><LinearGradient colors={['#EEE5F1','#FAF1EA']} style={StyleSheet.absoluteFill}/><T style={f.label}>MİNİK BİR KARŞILAŞTIRMA</T><FruitArt type={info.fruit} size={measure?176:140}/><T bold style={{fontSize:23}}>{info.fruitName} büyüklüğünde</T><T style={f.meta}>Her bebek kendi hızında büyür.</T><View style={r.stats}><View style={r.stat}><T style={f.meta}>Yaklaşık boy</T><T bold style={{fontSize:24}}>{formatLength(info.lengthCm)}</T></View><View style={r.stat}><T style={f.meta}>Yaklaşık ağırlık</T><T bold style={{fontSize:24}}>{formatWeight(info.weightG)}</T></View></View></View>
    {measure?<><Hint>Meyve karşılaştırmaları boyutu hayal etmene yardımcı olur. Ekrandaki görsel gerçek fiziksel boyutu göstermez; ölçüler kişisel ultrason sonucunun yerine geçmez.</Hint><Button onPress={()=>navigate('week',{week})}>Bu haftanın gelişimini oku</Button><View style={[f.row,{justifyContent:'space-between'}]}><Button secondary disabled={week===4} onPress={()=>setWeek(week-1)}>← Önceki</Button><Button secondary disabled={week===40} onPress={()=>setWeek(week+1)}>Sonraki →</Button></View></>:<>
    <RowLink title="Ölçü rehberini aç" subtitle="Haftalar arasında boyutu karşılaştır" art={`fruit_${info.fruit}`} onPress={()=>navigate('measure',{week})}/>
    <Chips items={[{id:'baby',title:'Bebeğinde'},{id:'mom',title:'Sende'},{id:'notes',title:`Notların (${notes.length})`}]} value={section} onChange={setSection}/>
    {section!=='notes'?<Card style={{gap:16}}><T bold style={{fontSize:19}}>{section==='baby'?'Küçük dünyasında neler oluyor?':'Bu hafta kendine de kulak ver'}</T>{info[section].map((text,i)=><View key={i} style={[f.row,{alignItems:'flex-start'}]}><View style={r.number}><T bold style={{color:colors.purple,fontSize:12}}>{i+1}</T></View><T style={[f.body,{flex:1}]}>{text}</T></View>)}<T style={f.meta}>Haftalık bilgiler geneldir; deneyimler ve ölçümler kişiden kişiye değişebilir.</T></Card>:<>
    <Field label="Bu haftadan hatırlamak istediğin" value={note} onChangeText={setNote} multiline placeholder="Bir his, ilk kıpırtı, küçük bir an…"/><Button disabled={!note.trim()} onPress={()=>{update(old=>({journal:[{id:uid(),title:`${week}. haftadan bir an`,text:note.trim(),date:localDay(),week},...old.journal]}));setNote('');toast('Haftalık notun kaydedildi');}}>Notumu sakla</Button>
    {notes.map(n=><Card key={n.id}><T style={f.meta}>{n.date}</T><T style={f.body}>{n.text}</T></Card>)}
    </>}
    <ReadingRail week={week} navigate={navigate} state={state}/></>}
  </Page>;
}
export function TodayExtras({state,navigate}) {const {week,remaining}=pregnancyAt(state);return <View style={{gap:12}}><RowLink title="Yolculuğun" subtitle={state.dueDate?`${remaining>0?`${remaining} gün kaldı`:'Beklenen tarihin geldi'} · Tarihlerini düzenle`:'Tahmini doğum tarihini ekle'} icon="calendar" onPress={()=>navigate('profile')}/><Section title="Küçük hazırlıklar" action="Tüm araçlar" onPress={()=>navigate('tracker')}/><View style={f.row}>{[{title:'Hastane çantam',art:'card_hospital_bag',route:'checklist',data:{list:'bag'}},{title:'Kilo günlüğüm',art:'card_scale',route:'weight'}].map(item=><Tap key={item.title} label={item.title} onPress={()=>navigate(item.route,item.data)} style={r.quick}><Image source={generatedAssets[item.art]} style={{width:70,height:64}} resizeMode="contain"/><T bold style={{fontSize:13}}>{item.title}</T><T style={f.meta}>Aç →</T></Tap>)}</View><ReadingRail week={week} navigate={navigate} state={state}/><RowLink title="Kendine bir not bırak" subtitle="Bu günün küçük bir anısını sakla" art="blog_postpartum_selfcare" onPress={()=>navigate('journal')}/></View>;}
const r=StyleSheet.create({articleRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:13,borderBottomWidth:1,borderColor:colors.line},thumb:{height:85,width:85,borderRadius:15},cover:{height:245,borderRadius:23,overflow:'hidden',marginTop:6},coverCopy:{position:'absolute',bottom:22,left:22,right:18,gap:12},topic:{width:143,paddingBottom:8},topicImage:{width:143,height:103,borderRadius:17},articleCover:{width:'100%',height:210,borderRadius:22},week:{width:46,minHeight:53,borderRadius:17,alignItems:'center',justifyContent:'center',gap:3,backgroundColor:'#F0EAEF'},fruitStage:{borderRadius:24,overflow:'hidden',padding:22,alignItems:'center',gap:10},stats:{flexDirection:'row',alignSelf:'stretch',marginTop:10},stat:{flex:1,alignItems:'center',gap:5},number:{width:27,height:27,borderRadius:14,backgroundColor:colors.lavender,alignItems:'center',justifyContent:'center'},quick:{flex:1,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:colors.line,borderRadius:20,padding:14,gap:8}});
